micronaut:
  application:
    name: bttc
  server:
    dual-protocol: true
    ssl:
      enabled: true
    port: 80
  ssl:
    port: 443
datasources:
  default:
    dialect: ORACLE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    ocid: ${DB_OCID}
    walletPassword: ${DB_WALLET_PASSWORD}
    connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
jpa.default.properties.hibernate.show_sql: true
mqtt:
  client:
    server-uri: ${MQTT_SERVER_URI}
    client-id: bttc-client-prod
    user-name: ${MQTT_USERNAME}
    password: ${MQTT_PASSWORD}
codes:
  recursive:
    xbox-gamertag: ${XBOX_GAMERTAG}
cod:
  sso-token:
oci:
  config:
    instance-principal:
      enabled: true
acme:
  enabled: true
  tos-agree: true
  cert-location: /certs
  domains:
    - ${DOMAIN_NAME}
  domain-key: |
    ${SSL_BTTC_KEY}
  account-key: |
    ${SSL_ACME_KEY}
  acme-server: https://acme-v02.api.letsencrypt.org/directory
  challenge-type: http