kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: insulin-helper
  namespace: default
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - 'bttc.toddrsharp.com'
      secretName: bttc-tls-cert
  rules:
    - host: bttc.toddrsharp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: bttc-client
              servicePort: 80
status:
  loadBalancer:
    ingress:
      - ip: 129.153.205.125