package codes.recursive.model;

import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.util.CollectionUtils;

import java.util.Map;

@Introspected
public class CallOfDuty {
    public static String MODERN_WARFARE = "mw";
    public static String COLD_WAR = "cw";
    public static String VANGUARD = "vg";

    public static Map MAPS = CollectionUtils.mapOf(
            "mw-mp_hackney_yard", "Hackney Yard (Night)",
            "mw-mp_aniyah", "Aniyah Palace",
            "mw-mp_euphrates", "Euphrates Bridge",
            "mw-mp_raid", "Grazna Raid",
            "mw-mp_m_pine", "Pine",
            "mw-mp_m_stack", "Stack",
            "mw-mp_deadzone", "Arklov Peak",
            "mw-mp_quarry2", "Karst River Quarry",
            "mw-mp_m_overunder", "Docks",
            "mw-mp_cave_am", "Azhir Cave",
            "mw-mp_cave", "Azhir Cave (Night)",
            "mw-mp_runner", "Gun Runner",
            "mw-mp_runner_pm", "Gun Runner (Night)",
            "mw-mp_hackney_am", "Hackney Yard",
            "mw-mp_piccadilly", "Piccadilly",
            "mw-mp_spear", "Rammaza",
            "mw-mp_spear_pm", "Rammaza (Night)",
            "mw-mp_petrograd", "St. Petrograd",
            "mw-mp_m_hill", "Hill",
            "mw-mp_m_king", "King",
            "mw-mp_m_speedball", "Speedball",
            "mw-mp_m_showers", "Gulag Showers",
            "mw-mp_downtown_gw", "Tarvosk District",
            "mw-mp_m_speed", "Shoot House",
            "mw-mp_farms2_gw", "Krovnik Farmland",
            "mw-mp_port2_gw", "Port",
            "mw-mp_crash2", "Crash",
            "mw-mp_vacant", "Vacant",
            "mw-mp_shipment", "Shipment",
            "mw-mp_m_cargo", "Cargo",
            "mw-mp_m_cage", "Atrium",
            "mw-mp_m_overwinter", "Docks",
            "mw-mp_emporium", "Atlas Superstore",
            "mw-mp_rust", "Rust",
            "mw-mp_boneyard_gw", "Zhokov Boneyard",
            "mw-mp_m_fork", "Bazaar",
            "mw-mp_donetsk", "Verdansk",
            "mw-mp_hideout", "Khandor Hideout",
            "mw-loading_mp_hideout", "Khandor Hideout",
            "mw-mp_aniyah_tac", "Aniyah Incursion",
            "mw-mp_backlot2", "Talsik Backlot",
            "mw-mp_village2", "Hovec Sawmill",
            "mw-mp_hardhat", "Hardhat",
            "mw-mp_m_wallco2", "Aisle 9",
            "mw-mp_donetsk2", "Verdansk",
            "mw-mp_scrapyard", "Zhokov Scrapyard",
            "mw-mp_m_trench", "Trench",
            "mw-mp_promenade_gw", "Barakett Promenade",
            "mw-mp_don3", "Verdansk",
            "mw-mp_garden", "Cheshire Park",
            "mw-mp_oilrig", "Petrov Oil Rig",
            "mw-mp_harbor", "Suldal Harbor",
            "mw-mp_layover_gw", "Verdansk International Airport",
            "mw-mp_m_cornfield", "Livestock",
            "mw-mp_m_stadium", "Verdansk Stadium",
            "mw-mp_malyshev", "Mialstor Tank Factory",
            "mw-mp_malyshev_10v10", "Mialstor Tank Factory",
            "mw-mp_broadcast2", "Broadcast",
            "mw-mp_riverside_gw", "Verdansk Riverside",
            "mw-mp_m_train", "Station",
            "mw-mp_kstenod", "Verdansk (Night)",
            "mw-mp_escape2", "Rebirth",
            "mw-mp_herat", "Al-Raab Airbase",
            "mw-mp_killhouse", "Killhouse",
            "mw-mp_m_drainage", "Drainage",
            "cw-mp_cartel", "Cartel",
            "cw-mp_tank", "Garrison",
            "cw-mp_miami", "Miami",
            "cw-mp_moscow", "Moscow",
            "cw-mp_satellite", "Satellite",
            "cw-mp_kgb", "Checkmate",
            "cw-wz_forest", "Ruka",
            "cw-wz_ski_slopes", "Alpine",
            "cw-mp_nuketown6", "Nuketown '84",
            "cw-mp_tundra", "Crossroads",
            "cw-mp_black_sea", "Armada",
            "cw-mp_mall", "The Pines",
            "cw-mp_raid_rm", "Raid",
            "cw-mp_sm_berlin_tunnel", "U-Bahn",
            "cw-mp_sm_finance", "KGB",
            "cw-mp_sm_game_show", "Game Show",
            "cw-mp_sm_central", "ICBM",
            "cw-wz_sanatorium", "Sanatorium",
            "cw-nuketown6_holiday", "Nuketown '84 Holiday",
            "cw-mp_express_rm", "Express",
            "cw-mp_apocalypse", "Apocalypse",
            "cw-mp_sm_market", "Mansion",
            "cw-mp_miami_strike", "Miami Strike",
            "cw-wz_golova", "Golova",
            "cw-mp_cliffhanger", "Yamantau",
            "cw-mp_sm_gas_station", "Diesel",
            "mw-mp_don4", "Verdansk '84",
            "cw-wz_duga", "Duga",
            "cw-mp_village_rm", "Standoff",
            "cw-mp_sm_amsterdam", "Amsterdam",
            "cw-mp_dune", "Collateral",
            "cw-mp_hijacked_rm", "Hijacked",
            "mw-mp_escape3", "Rebirth",
            "cw-mp_paintball_rm", "Rush",
            "cw-mp_sm_deptstore", "Showroom",
            "cw-mp_slums_rm", "Slums",
            "cw-mp_echelon", "Echelon",
            "cw-mp_drivein_rm", "Drive In",
            "cw-mp_zoo_rm", "Zoo",
            "cw-mp_firebase", "Deprogram",
            "cw-mp_amerika", "Amerika",
            "cw-mp_sm_vault", "Gluboko",
            "cw-mp_don4_pm", "Nuketown '84 Halloween",
            "mw-mp_don4_pm", "Verdansk Halloween",
            "vg-mp_berlin_01", "Berlin",
            "vg-mp_bocage_2", "Bocage",
            "vg-mp_castle2", "Castle",
            "vg-mp_whitehouse_2", "Das Haus",
            "vg-mp_destruct_01", "Decoy",
            "vg-mp_winter", "Demyansk",
            "vg-mp_elalamein", "Desert Siege",
            "vg-mp_dome2", "Dome",
            "vg-mp_nest2", "Eagle’s Nest",
            "vg-mp_gavutu2", "Gavutu",
            "vg-mp_royal_hotel", "Hotel Royal",
            "vg-mp_24h_hill_01", "Numa Numa",
            "vg-mp_oasis_v3", "Oasis",
            "vg-mp_red_star", "Red Star",
            "vg-mp_subpen", "Sub Pens",
            "vg-mp_tuscan", "Tuscan",
            "vg-mp_arena_evo", "Champion Hill",
            "vg-mp_shipment_s4", "Shipment"
    );

    public static String lookupMap(String game, String codeName) {
        return MAPS.get(game + "-" + codeName).toString();
    }
}
